### ISSUE TITLE
1x02 screw terminal - no device or package found

### ISSUE THREAD

**Issue by RafaelZasas** [LibrePCB-Libraries/LibrePCB_Connectors.lplib#19]
I would like to preface that I am learning electronics and PCB design.

I need a screw terminal for my project, but on the board view I get an error when trying to add the component to the board that says no device or package for the selected component found in the library. It asks me to add a suitable device or package to my workspace library.

I followed the youtube videos and installed all of the libraries available.

Do I need additional libraries for this connector, that includes the necessary files for the board view, and optionally a 3D model?

If so, where can I find such a library?

**Comment by RafaelZasas** [comment]
I also need other components- namely, BMP280 for altitude monitoring, MPU6050 accelerometer + gryoscope and NEO-6M-GPS module. 

I am using Flux.ai for learning purposes thanks to their built in copilot. They have the components in their library, however their web based app is slow and the 3D rendering is unusable. I would prefer to use Libre PCB but I have no idea how to import the components I need for this project.

Any help would be appreciated.

**Comment by ubruhin** [comment]
Hi,
These devices don't exist yet but you can easily create them by yourself, see this FAQ item for details: https://librepcb.org/faq/#where-is-library-element
